Repository wordpress-mobile/WordPress-iOS-Shared, pull requests merged in 2019-04, with the labels that each got.

#197 [Jetpack Remote Install] Add new analytics events
  WordPressShared.podspec
  WordPressShared/Core/Analytics/WPAnalytics.h
Labels: Analytics Events

#198 Podspec version fixed
  WordPressShared.podspec
Labels: bug

#196 Update dependencies for 1.7.4
  Podfile
  Podfile.lock
Labels: enhancement

#199 Adds URL validation as an extension to String.
  WordPressShared.xcodeproj/project.pbxproj
  WordPressShared/Core/Utility/String+URLValidation.swift
  WordPressSharedTests/StringURLValidationTests.swift
Labels: enhancement

#202 Moves WPiOS's Debouncer into WPiOS Shared.
  WordPressShared.podspec
  WordPressShared.xcodeproj/project.pbxproj
  WordPressShared/Core/Utility/Debouncer.swift
  WordPressSharedTests/DebouncerTests.swift
Labels: enhancement

#201 Support Swift 5
  .circleci/config.yml
  .swift-version
  Podfile
  Podfile.lock
  WordPressShared.podspec
  WordPressShared.xcodeproj/project.pbxproj
  WordPressShared.xcodeproj/xcshareddata/xcschemes/WordPressShared.xcscheme
  WordPressShared/Core/Logging/CocoaLumberjack.swift
  WordPressShared/Core/Utility/String+Helpers.swift
Labels: enhancement
