Repository wordpress-mobile/WordPress-iOS-Shared, pull requests merged in 2020-03, with the labels that each got.

#255 Release 1.8.15
  WordPressShared.podspec
Labels: releases

#258 Pin the ruby version for this project
  .ruby-version
Labels: enhancement

#257 Extend WPAnalytics to decentralize tracks
  WordPressShared.podspec
  WordPressShared/Core/Analytics/WPAnalytics.h
  WordPressShared/Core/Analytics/WPAnalytics.m
  WordPressSharedTests/TestAnalyticsTracker.m
  WordPressSharedTests/WPAnalyticsTests.m
Labels: Analytics Events, enhancement

#259 Merge release 1.8.16 back into develop
  WordPressShared.podspec
Labels: releases
